### ISSUE TITLE
INCLUDE files support

### ISSUE THREAD

**Issue by Gury8** [mariusz-buk/effectus#7]
Support for INCLUDE directive (to include additional Action! source files) is missing.

**Comment by mariusz-buk** [comment]
This stops me from starting coding in Effectus. How much work is it?

**Comment by Gury8** [comment]
I will work on it very soon. I know this is very important feature, I will yet have to see how much work it will bring in.

**Comment by Gury8** [comment]
INCLUDE directive is supported now!

- Files can be included, starting in the same directory as main compiled listing code
- Currently one level of included files is supported. This means only main listing program can read other files with the use of INCLUDE directive (this directive will be ignored in included files)
- File is ignored if it isn't found

Example:
  INCLUDE "D1:LIBRARY.EFF"
  INCLUDE "H1:lib_test.eff"
  INCLUDE "TEST01.EFF"
